### ISSUE TITLE
Set up question

### ISSUE THREAD

**Issue by sympmarc** [estruyf/vscode-sparkup#1]
Hey, there. I like the looks of this and would like to try it out. I'm probably being a dummy, but I can't figure out where to put the API key. When I installed the extension, I didn't get the Welcome screen, and I'm not sure where to look for the settings. PC, Windows 11

**Comment by estruyf** [comment]
Hey @sympmarc, thanks for trying it. Happy to hear your experience.

I have written a tutorial, hope this will help you: https://rapidapi.com/eliostruyf/api/sparkup/tutorials/using-the-api-in-combination-with-the-sparkup---visual-studio-code-extension

If not, let me know.

**Comment by sympmarc** [comment]
Actually, I think I got it. I was trying to follow the tutorial here: https://rapidapi.com/eliostruyf/api/sparkup/tutorials/using-the-api-in-combination-with-the-sparkup---visual-studio-code-extension

**Comment by sympmarc** [comment]
I'm getting results back. It would be great if there were a way to see what it's specifically changing.

**Comment by sympmarc** [comment]
But I like it!

**Comment by estruyf** [comment]
What would be your preferred option:
- Update the text
- Provide previews (like it's done for headlines)
